### ISSUE TITLE
error while deploying

### ISSUE THREAD

**Issue by artem-schander** [metalmatze/digitalocean_exporter#29]
I've forked this repo and wanted to deploy a digital ocean app, but it wont work.
This is the output:
> [2024-09-11 11:38:21] │ error building image: error building stage: failed to optimize instructions: failed to get files used from context: failed to get fileinfo for /.app_platform_workspace/digitalocean_exporter: lstat /.app_platform_workspace/digitalocean_exporter: no such file or directory

I assume it is related to this.
https://github.com/metalmatze/digitalocean_exporter/blob/6bb00cbf1f8fc56ab7b0dd996ef00308d2fd6303/Dockerfile#L4

There is no file named `digitalocean_exporter` in the same directory as the Dockerfile

**Comment by artem-schander** [comment]
UPDATE

I was able to get it running. but not via github. I used the docker hub method.
So the issue remains, but is not urgent at all.

**Comment by JoshuwayMorris** [comment]
Hey @Artem-Schander,
I was having a similar issue myself this morning. 

I started by cloning the repository, and then I added a `docker-compose.yaml` file with the following:
```
  digital-ocean-exporter:
    build:
      dockerfile: Dockerfile
    environment:
      DIGITALOCEAN_TOKEN: "CHANGE_ME"
    networks:
      - localprom
    ports:
      - "9212:9212"
```

However, the `Dockerfile` that exists in the repository includes the line:
```
 ADD ./digitalocean_exporter /usr/bin/digitalocean_exporter 
```

The repository does not include any pre-build binaries, so the start of that line `./digitalocean_exporter` does not exist. For it to exist, you will first need to compile the project using "Go".

You can install Go from their website, and then build the project using `go build`. The Dockerfile will then run successfully.

Hope that also helps for anyone else in the future. Thanks!
